name: flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  flutter_bloc: ^7.0.0
  flutter_html: ^1.3.0
  get: ^4.1.4
  get_it: ^6.1.1
  http: ^0.13.1
  rive_splash_screen: ^0.1.0
  shared_preferences: ^2.0.5
  sliding_up_panel: ^2.0.0+1
  url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/rive/
    - assets/translations/
